#!/bin/sh

if ! command -v stow > /dev/null 2>&1;then
    echo "stow not found. please install stow"
    exit 1
fi

mkdir -p \
    "$HOME/.config" \
    "$HOME/.config/git" \
    "$HOME/lib/bin" \
    "$HOME/.local/" \
    "$HOME/.local/bin" \
    "$HOME/.local/etc" \
    "$HOME/.local/libexec" \
    "$HOME/.local/share/fonts" \
    "$HOME/.lein/" \
    "$HOME/.cache/"

if [ ! -f "$HOME/.emacs.d" ]; then
    git clone https://github.com/hlissner/doom-emacs.git $HOME/.emacs.d
fi

_pkgs=$(find . -maxdepth 1 -type d ! -path "*/system" ! -path "*/.git" ! -path "." ! -path "*/scripts" -print | sed 's|\./||' )
case $1 in
    "u"|"uninstall")
        echo "unstowing"
        echo "$_pkgs" | xargs stow -D
        exit 0
        ;;
    *)
        echo "restowing"
        echo "$_pkgs" | xargs stow -R
        exit 0
        ;;
esac
