#!/bin/sh

if ! command -v stow > /dev/null 2>&1;then
    echo "stow not found. please install stow"
    exit 1
fi

mkdir -p \
    "$HOME/.config" \
    "$HOME/.config/git" \
    "$HOME/.config/zsh" \
    "$HOME/lib/bin" \
    "$HOME/.local/" \
    "$HOME/.local/bin" \
    "$HOME/.local/etc" \
    "$HOME/.local/libexec" \
    "$HOME/.local/share/applications" \
    "$HOME/.local/share/fonts" \
    "$HOME/.lein/" \
    "$HOME/.cache/"

if [ ! -d "$HOME/.emacs.d" ]; then
    git clone https://github.com/hlissner/doom-emacs.git $HOME/.emacs.d
fi

if [ "Darwin" = "$(uname)" ]; then
    _pkgs="apps doom git lib macosx shell tmux vim gpg"
elif uname -r|grep -q microsoft;then
    _pkgs="apps doom git lib shell tmux vim gpg"
else
    _pkgs="apps doom git lib shell tmux vim email weechat sway gpg"
fi


case $1 in
    "u"|"uninstall")
        echo "unstowing"
        echo "$_pkgs" | xargs stow -D
        exit 0
        ;;
    *)
        echo "restowing"
        echo "$_pkgs" | xargs stow -R
        exit 0
        ;;
esac
