(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(package-selected-packages
   (quote
    (yapfify web-mode neotree leuven-theme highlight-indentation git-link flycheck-pos-tip exec-path-from-shell dumb-jump doom-themes all-the-icons memoize disaster company-shell color-theme-sanityinc-tomorrow clojure-snippets clj-refactor cider seq adaptive-wrap evil helm helm-core alert org-plus-contrib magit magit-popup git-commit async js2-mode flycheck yaml-mode xterm-color x86-lookup ws-butler with-editor winum which-key web-beautify volatile-highlights vimrc-mode vi-tilde-fringe uuidgen use-package unfill undo-tree toc-org tide tagedit symon subatomic256-theme subatomic-theme string-inflection stickyfunc-enhance srefactor sql-indent spaceline smeargle slim-mode shell-pop scss-mode sass-mode restart-emacs rainbow-mode rainbow-identifiers rainbow-delimiters queue pyvenv pytest pyenv-mode py-isort pug-mode pos-tip popwin pip-requirements phpunit phpcbf php-extras php-auto-yasnippets persp-mode pcre2el paredit paradox orgit org-projectile org-present org-pomodoro org-download org-bullets open-junk-file nasm-mode multi-term move-text mmm-mode material-theme markdown-toc magit-gitflow macrostep lua-mode lorem-ipsum log4e livid-mode live-py-mode linum-relative link-hint less-css-mode json-mode js2-refactor js-doc insert-shebang info+ inflections indent-guide ibuffer-projectile hy-mode hungry-delete htmlize hl-todo highlight-parentheses highlight-numbers hide-comnt help-fns+ helm-themes helm-swoop helm-pydoc helm-purpose helm-projectile helm-mode-manager helm-make helm-gitignore helm-flx helm-descbinds helm-css-scss helm-company helm-c-yasnippet helm-ag gruvbox-theme goto-chg google-translate golden-ratio gnuplot gntp gitconfig-mode gitattributes-mode git-timemachine git-messenger gh-md fzf fuzzy font-lock+ flx-ido flatland-theme fish-mode fill-column-indicator fancy-battery eyebrowse expand-region evil-visualstar evil-visual-mark-mode evil-unimpaired evil-tutor evil-surround evil-snipe evil-search-highlight-persist evil-numbers evil-nerd-commenter evil-mc evil-matchit evil-magit evil-lisp-state evil-indent-plus evil-iedit-state evil-exchange evil-escape evil-ediff evil-args evil-anzu eshell-z eshell-prompt-extras esh-help emmet-mode elisp-slime-nav edn editorconfig drupal-mode define-word dactyl-mode cython-mode csv-mode company-web company-tern company-statistics company-c-headers company-anaconda column-enforce-mode color-identifiers-mode coffee-mode cmake-mode clojure-mode clean-aindent-mode clang-format cider-eval-sexp-fu auto-yasnippet auto-highlight-symbol auto-compile aggressive-indent ace-window ace-link ace-jump-helm-line ac-ispell))))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
