#!/bin/zsh

# zgen setup
export MINIPLUG_HOME=~/.cache/miniplug

# auto-download zgen
if [[ ! -f ~/.cache/miniplug.zsh ]]; then
    curl -sL https://git.sr.ht/~yerinalexey/miniplug/blob/master/miniplug.zsh \
        -o ~/.cache/miniplug.zsh
fi
source ~/.cache/miniplug.zsh

# zsh-users
miniplug plugin 'zsh-users/zsh-syntax-highlighting'
miniplug plugin 'zsh-users/zsh-history-substring-search'
miniplug plugin 'zdharma/fast-syntax-highlighting'

# z
miniplug plugin 'skywind3000/z.lua'

# macosx stuff
miniplug plugin 'unixorn/tumult.plugin.zsh'

# git extra aliases and commands
miniplug plugin 'unixorn/git-extra-commands'

# fzf
miniplug plugin 'unixorn/fzf-zsh-plugin'

# sysadmin's toolkit.
miniplug plugin 'skx/sysadmin-util'

# Load more completion files for zsh from the zsh-lovers github repo.
miniplug plugin 'zsh-users/zsh-completions' src

# Very cool plugin that generates zsh completion functions for commands
# if they have getopt-style help text. It doesn't generate them on the fly,
# you'll have to explicitly generate a completion, but it's still quite cool.
miniplug plugin 'RobSis/zsh-completion-generator'

# Add Fish-like autosuggestions to your ZSH.
miniplug plugin 'zsh-users/zsh-autosuggestions'

# themes and colors
miniplug plugin 'chrissicool/zsh-256color'
miniplug plugin 'jedahan/geometry-hydrate'
miniplug theme 'geometry-zsh/geometry'

# load geometry plugins before geometry itself
export GEOMETRY_PROMPT_PLUGINS=(hydrate)

# Finally
# load all plugins
miniplug load

# Configure substring search
# Set keystrokes for substring searching
zmodload zsh/terminfo
bindkey "$terminfo[kcuu1]" history-substring-search-up
bindkey "$terminfo[kcud1]" history-substring-search-down

# load local completions last
GENCOMPL_FPATH=$HOME/.config/zsh/complete
