#!/bin/zsh

# zgen setup
export MINIPLUG_HOME=~/.cache/miniplug

# auto-download zgen
if [[ ! -f ~/.cache/miniplug.zsh ]]; then
    curl -sL https://git.sr.ht/~yerinalexey/miniplug/blob/master/miniplug.zsh \
        -o ~/.cache/miniplug.zsh
fi
source ~/.cache/miniplug.zsh

# autosuggest
miniplug plugin 'zsh-users/zsh-autosuggestions'

# syntax hilight
miniplug plugin 'zdharma/fast-syntax-highlighting'

# z
miniplug plugin 'skywind3000/z.lua'

# macosx stuff
miniplug plugin 'unixorn/tumult.plugin.zsh'

# git extra aliases and commands
miniplug plugin 'unixorn/git-extra-commands'

# sysadmin's toolkit.
miniplug plugin 'skx/sysadmin-util'

# git commdodity commands
miniplug plugin 'unixorn/git-extra-commands'

# Load more completion files for zsh from the zsh-lovers github repo.
miniplug plugin 'zsh-users/zsh-completions' src

# Very cool plugin that generates zsh completion functions for commands
# if they have getopt-style help text. It doesn't generate them on the fly,
# you'll have to explicitly generate a completion, but it's still quite cool.
miniplug plugin 'RobSis/zsh-completion-generator'

# themes and colors
miniplug plugin 'chrissicool/zsh-256color'
miniplug plugin 'jedahan/geometry-hydrate'
miniplug theme 'geometry-zsh/geometry'

# load geometry plugins before geometry itself
export GEOMETRY_PROMPT_PLUGINS=(hydrate)

# Finally
# load all plugins
miniplug load

# load local completions last
GENCOMPL_FPATH=$HOME/.config/zsh/complete

# Fix bracketed paste issue
# Closes #73
ZSH_AUTOSUGGEST_CLEAR_WIDGETS+=(bracketed-paste)
