#!/bin/zsh

declare -A ZINIT
ZINIT[HOME_DIR]=$HOME/.cache/zinit

if [[ ! -d $ZINIT[HOME_DIR]/bin ]]; then
    git clone https://github.com/zdharma/zinit $ZINIT[HOME_DIR]/bin
fi
source ~/.cache/zinit/bin/zinit.zsh

zinit for \
    light-mode  zsh-users/zsh-autosuggestions \
    light-mode  zdharma/fast-syntax-highlighting \
                zdharma/history-search-multi-word \
                skywind3000/z.lua \
                zsh-users/zsh-completions \
                zpm-zsh/autoenv \
                zpm-zsh/ls \
                zpm-zsh/helpers \
                mdumitru/fancy-ctrl-z \
                \
                zpm-zsh/material-colors \
                zpm-zsh/pretty-time \
                zpm-zsh/pr-is-root \
                zpm-zsh/pr-user \
                zpm-zsh/pr-return \
                zpm-zsh/pr-exec-time \
                zpm-zsh/pr-git \
                zpm-zsh/pr-cwd \
                zpm-zsh/pr-2 \
                zpm-zsh/pr-eol \
                zpm-zsh/pr-zcalc \
                zpm-zsh/pr-correct \
                zpm-zsh/colors \
                zpm-zsh/colorize \
    light-mode  zpm-zsh/minimal-theme

zplugin pack"default+keys" for fzf

zinit as"null" wait"3" lucid for \
    Fakerr/git-recall \
    paulirish/git-open \
    paulirish/git-recent \
    davidosomething/git-my \
    unixorn/git-extra-commands \
    make"PREFIX=$ZPFX install"  iwata/git-now \
    make"PREFIX=$ZPFX"          tj/git-extras

autoload -Uz _zinit
(( ${+_comps}  )) && _comps[zinit]=_zinit
