#!/bin/sh
[ "$TRACE" ] && set -xv
set -e

HOSTNAME="$(hostname)"

NAME=`basename $0`
LOCKDIR=/tmp/$UID-$USER/lock
mkdir -p $LOCKDIR

function _lock() {
    command=$@

    (
        flock -n 9 || exit 1

        $command
    ) 9>$LOCKDIR/$NAME
}
