#!/bin/sh
[ "$TRACE" ] && set -xv
set -e

HOSTNAME="$(hostname)"

NAME=`basename $0`
LOCKDIR=/tmp/$UID-$USER/lock
mkdir -p $LOCKDIR

function _lock() {
    (
        flock -n 9 || exit 1

        $@
        wait
    ) 9>$LOCKDIR/$NAME
}
