#!/bin/dash
# vim: ft=sh
[ "$TRACE" ] && set -xv

_run() {
	name=$1
	command=$@
	if [ ! $(pgrep -u $USER $name >/dev/null 2>&1) ]; then
		$command &
	fi
}

#
# AutoStart
#

#
# DBus - Start if not running
#
if which dbus-launch >/dev/null && test -z "$DBUS_SESSION_BUS_ADDRESS"; then
	eval "$(dbus-launch --sh-syntax --exit-with-session)"
fi

# Notification Daemon
_run dunst -conf $HOME/.config/dunst/dunstrc

# Compositor
_run compton --dbus --config $HOME/.config/compton/compton.conf -b

# Conky
_run conky -c $HOME/.config/bspwm/conkyrc -d

# GNU Privacy Guard
_run gpg-agent

# clipboard menu
_run parcellite -d

#
# Wallpaper set
#
[ -x "$HOME/.config/wallpapers/set" ] && $HOME/.config/wallpapers/set &

#
# Polkit agent
#
_run lxpolkit

#
# LXSession for the rest
#
_run lxsession

#
# Polybar
#
# select primary monitor
export PRIMARY_MONITOR="$(xrandr | grep primary | cut -d' ' -f1)"
_run polybar -r bar

#
# Laptop Power management
#
[ "$(hostname)" = "red" ] && _run xfce4-power-management
