#!/bin/bash
# set -e
[ "$TRACE" ] && set -xv

#   ___.
#  \_ |__   ______________  _  _______
#   | __ \ /  ___/\____ \ \/ \/ /     \
#   | \_\ \\___ \ |  |_> >     /  Y Y  \
#   |___  /____  >|   __/ \/\_/|__|_|  /
#       \/     \/ |__|               \/

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc config normal_border_color   '#282828'
bspc config focused_border_color  '#d5c4a1'
bspc config active_border_color   '#1d2021'

bspc config top_padding     8
bspc config left_padding    8
bspc config right_padding   8
bspc config bottom_padding  8

bspc config border_width	3
bspc config window_gap		18

bspc config split_ratio             0.50
bspc config single_monocle          true
bspc config gapless_monocle         false
bspc config paddingless_monocle     false
bspc config borderless_monocle      false


bspc config focus_follows_pointer   true
bspc config pointer_follows_monitor true

bspc config click_to_focus          true
bspc config swallow_first_click     true
#
# * this creates a LOT of unexpected behaviors
# bspc config pointer_follows_focus   true

#                 _ _
#  _ __  ___ _ _ (_) |_ ___ _ _
# | '  \/ _ \ ' \| |  _/ _ \ '_|
# |_|_|_\___/_||_|_|\__\___/_|
#                  configuration
#
I=1
M=$(bspc query -M | wc -l)
if [[ "$M" == 1 ]]; then
    bspc monitor -d I II III IV V
elif [[ "$M" == 2 ]]; then
    bspc monitor $(bspc query -M | awk NR==1) -d I II III
    bspc monitor $(bspc query -M | awk NR==2) -d IV V VI VII VIII IX
else
    for monitor in $(bspc query -M); do
        bspc monitor $monitor \
            -n "$I" \
            -d $I/{a,b,c}
        let I++
    done
fi

#      node _
#  _ _ _  _| |___ ___
# | '_| || | / -_|_-<
# |_|  \_,_|_\___/__/

# Clear the rules before adding any
while read -r rule _; do bspc rule -r "$rule"; done < <(bspc rule -l)

bspc rule -a monitor=0 split_dir=east

bspc rule -a screenkey --unmanage

bspc rule -a GtkFileChooserDialog       state=floating --center --focus
bspc rule -a Pinentry                   state=floating --center --focus
bspc rule -a gcolor2                    state=floating center=true
bspc rule -a lxappearance               state=floating center=true
bspc rule -a file-roller                state=pseudo_tiled
bspc rule -a conky                      sticky=on manage=off lower=on
bspc rule -a Docky                      layer=above border=off manage=on
# Browsers
bspc rule -a google-chrome-unstable     private=on
bspc rule -a google-chrome-stable       private=on
bspc rule -a chromium                   private=on
bspc rule -a Firefox                    private=on
bspc rule -a Firefox:SessionManager     state=floating layer=above
bspc rule -a Toplevel:Firefox           state=floating
bspc rule -a Firefox:Dialog             state=floating

# reclaim orphan windows
bspc wm -o

# add scripts to $PATH for sxhkd
export PATH=$PATH:$HOME/.config/bspwm/scripts

# start
# if [ ! pgrep -u $USER sxhkd >/dev/null 2>&1 ];then
    [ -e "/bin/dash" ] && export SXHKD_SHELL=/bin/dash
    sxhkd &
#fi

# autostart
$HOME/.config/bspwm/autostart &
