#!/bin/zsh

ARANDR_CONFIG=${ARANDR_CONFIG:-$HOME/.screenlayout}

presets="$(find $ARANDR_CONFIG/ -maxdepth 1 -type f -printf '%f\n')\narandr"
choice="$(echo $presets | rofi -dmenu -p 'Screenlayout: ')"

if [ "$choice" = "arandr"]; then
    arandr &
else
    $ARANDR_CONFIG/$choice
fi
