#!/bin/sh
# vim: ft=sh
[ "$TRACE" ] && set -xv

_run() {
    program=$1
    command=$@
    if [ ! $(pgrep -u $USER $program>/dev/null 2>&1) ]; then
        $command &
    fi
}

HOSTNAME="$(hostname)"

#
# AutoStart
#

#
# DBus - Start if not running
#
if which dbus-launch >/dev/null && test -z "$DBUS_SESSION_BUS_ADDRESS"; then
    eval "$(dbus-launch --sh-syntax --exit-with-session)"
fi

# Notification Daemon
_run dunst -conf $HOME/.config/dunst/dunstrc

# Compositor
_run compton --dbus --config $HOME/.config/compton/compton.conf -b

# Conky
#_run conky -c $HOME/.config/bspwm/conkyrc -d

# GNU Privacy Guard
_run gpg-agent

#
# Wallpaper set
#
[ -x "$HOME/.config/wallpapers/set" ] && $HOME/.config/wallpapers/set &

#
# Polkit agent
#
# _run lxpolkit

#
# LXSession for the rest
#
# _run lxsession
_run xfsettingsd

#
# Polybar
#
# select primary monitor
case $HOSTNAME in
    red)
        export PRIMARY_MONITOR=eDP-1
        ;;
    *)
        export PRIMARY_MONITOR="$(xrandr | grep primary | cut -d' ' -f1)"
    ;;
esac
_run polybar -r bar

#
# Laptop Power management
#
[ $HOSTNAME = "red" ] && _run xfce4-power-management

#
# mons daemon
#
[ $HOSTNAME = "red" ] && _run mons -a

#
# Lock screen
#

if [ $HOSTNAME = "red" ]; then
    $HOME/.cargo/bin/xidlehook \
        --time 5 \
        --timer 'light -S 50; slock' \
        --notify 10 \
        --notifier  'light -S 1' \
        --canceller 'light -S 50' \
        --not-when-fullscreen \
        --not-when-audio &
fi
