#!/bin/sh
set -e

case "$(hostname)" in
    "cli.mb")
        exec feh --bg-tile $HOME/.config/wallpapers/giove2.jpg
        ;;
    *)
        exec feh --bg-tile $HOME/.config/wallpapers/pattern.jpg
        ;;
esac
